### ISSUE TITLE
Just a little confused

### ISSUE THREAD

**Issue by zRains** [minijaham/FeedHealCMD#6]
- Does the releases update synchronously？
- More detailed command description？
- How is going today?

**Comment by minijaham** [comment]
1. I will have to manually upload releases(I haven't been doing so in a while)
2. I will add them xD
3. I'm doing very good! How about you?

**Comment by minijaham** [comment]
Oops accidentally closed it

Edit: I have invited you as a collaborator, so if you would like, you can edit the files directly. Thank you!

**Comment by zRains** [comment]
Of course i will, thank you for your invitation. In fact, I accepted the invitation very early, but I'm not familiar with GitHub yet.:laughing:
This is my plan for the future of this plugin:
- More commands
I think only two orders are too few. We can add more commands！
`/effect < player > < effect > [seconds] [amplifier] [hideparticles] or / effect < player > clear`
The built-in effect command is cumbersome. I want to simplify it. Just like you said `/speed`
- UI
Use form operation to make commands more convenient. It can be set for single player or all players.

I think I'll open a new branch:smile:

**Comment by minijaham** [comment]
Alright! Thank you for the massive help! xD
